import { useState } from 'react';
import { Link2, LogOut, MessageSquareText, RefreshCw, Smartphone, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { sessionsApi, type Session } from '../../lib/api';
import { useSessionMutation } from '../../hooks/use-sessions';
import { StatusBadge } from '../ui/StatusBadge';
import { Modal } from '../ui/Modal';
const state=(s:Session)=>s.state||s.status||'unknown';const online=(s:Session)=>['open','connected','online'].includes(state(s).toLowerCase());const pending=(s:Session)=>['connecting','pending','qr'].includes(state(s).toLowerCase());const number=(s:Session)=>s.number||s.ownerJid?.split('@')[0]||'Not paired';
export function SessionCard({session:s,full=false,onDetails}:{session:Session;full?:boolean;onDetails?:()=>void}){const[qr,setQr]=useState<string|null>(null);const m=useSessionMutation();const busy=m.restart.isPending||m.disconnect.isPending||m.remove.isPending;const act=async(fn:()=>Promise<unknown>,ok:string)=>{try{await fn();toast.success(ok)}catch(e){toast.error(e instanceof Error?e.message:'Action failed')}};const connect=async()=>{try{const d=await sessionsApi.connect(s.instanceName!);const image=d.base64||d.qrcode||d.qr||d.code;if(image)setQr(image.startsWith('data:image')?image:`data:image/png;base64,${image}`);else toast.success('Connection request sent')}catch(e){toast.error(e instanceof Error?e.message:'Could not connect')}};return <article className="card"><div className="cardTop"><button className="avatar" aria-label={`Open ${s.instanceName}`} onClick={onDetails}><Smartphone size={19}/></button><div className="sessionTitle"><strong>{s.instanceName||'Unnamed'}</strong><span>{s.profileName||number(s)}</span></div><StatusBadge connected={online(s)} pending={pending(s)}/></div><div className="divider"/><div className="meta"><Meta label="Number" value={number(s)}/><Meta label="State" value={state(s)}/><Meta label="Token" value={s.tokenKnown?'Server-side':'Evolution'}/></div><div className="cardActions"><button disabled={busy} onClick={()=>void connect()}><Link2 size={14}/>{online(s)?'Status':'Connect'}</button>{online(s)&&<button onClick={onDetails}><MessageSquareText size={14}/>Message</button>}<button onClick={onDetails}>Details</button></div>{full&&<div className="cardActions"><button disabled={busy} onClick={()=>void act(()=>m.restart.mutateAsync(s.instanceName!),'Restart requested')}><RefreshCw size={14}/>Restart</button><button disabled={busy} onClick={()=>void act(()=>m.disconnect.mutateAsync(s.instanceName!),'Logged out')}><LogOut size={14}/>Logout</button><button className="danger" disabled={busy} onClick={()=>void act(()=>m.remove.mutateAsync(s.instanceName!),'Session deleted')}><Trash2 size={14}/>Delete</button></div>}{qr&&<Modal title={`Connect · ${s.instanceName}`} close={()=>setQr(null)}><div className="qrWrap"><img src={qr} alt="WhatsApp QR code"/><strong>Scan with WhatsApp → Linked devices</strong><span>Keep this window open while pairing.</span></div></Modal>}</article>}
function Meta({label,value}:{label:string;value:string}){return <div><small>{label}</small><span>{value}</span></div>}
