import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, MessageSquare, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { crmApi, type Lead, type LeadStatus } from '../lib/api';
const statuses:LeadStatus[]=['new','contacted','qualified','won','lost'];
export function LeadDetailPage(){
 const {id}=useParams();const nav=useNavigate();const [lead,setLead]=useState<Lead|null>(null);const [note,setNote]=useState('');
 const load=async()=>{if(!id)return;try{setLead(await crmApi.getLead(id))}catch(e){toast.error(e instanceof Error?e.message:'Could not load lead.')}};
 useEffect(()=>{void load()},[id]);
 if(!lead)return <div className="loading">Loading lead…</div>;
 const save=async(patch:Partial<Lead>,activityText?:string)=>{try{const next=await crmApi.updateLead(lead.id,{...patch,activityText});setLead({...lead,...next});}catch(e){toast.error(e instanceof Error?e.message:'Could not update lead.')}};
 const remove=async()=>{if(!confirm('Delete this lead?'))return;try{await crmApi.removeLead(lead.id);toast.success('Lead deleted');nav('/leads')}catch(e){toast.error(e instanceof Error?e.message:'Could not delete lead.')}};
 return <div className="crmPage"><Link to="/leads" className="backLink"><ArrowLeft size={14}/> Back to leads</Link><section className="hero detailHero"><div><p className="eyebrow">LEAD</p><h1>{lead.name}</h1><p>{lead.source} · {lead.phone||'No WhatsApp number'}</p></div><div className="cardActions"><Link className="secondary" to={`/inbox?instance=&jid=${encodeURIComponent(lead.phone)}`}><MessageSquare size={14}/> Open inbox</Link><button className="dangerButton" onClick={()=>void remove()}><Trash2 size={14}/> Delete</button></div></section><div className="leadDetailGrid"><section className="card"><div className="sectionHeading"><h2>Details</h2><span className={`status ${lead.status}`}>{lead.status}</span></div><div className="form two"><label>Phone<input value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})} onBlur={()=>void save({phone:lead.phone})}/></label><label>Email<input value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})} onBlur={()=>void save({email:lead.email})}/></label><label>Company<input value={lead.company} onChange={e=>setLead({...lead,company:e.target.value})} onBlur={()=>void save({company:lead.company})}/></label><label>Status<select value={lead.status} onChange={e=>{const v=e.target.value as LeadStatus;setLead({...lead,status:v});void save({status:v},`Status changed to ${v}`)}}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label className="span2">Tags<input value={lead.tags.join(', ')} onChange={e=>setLead({...lead,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} onBlur={()=>void save({tags:lead.tags})}/></label><label className="span2">Notes<textarea value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})} onBlur={()=>void save({notes:lead.notes})}/></label></div></section><section className="card"><div className="sectionHeading"><h2>Activity</h2></div><div className="form"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add an activity note"/><button className="primary" onClick={async()=>{if(!note.trim())return;await save({},note);setNote('');void load()}}>Add note</button></div><div className="activityList">{lead.activity.map(a=><div key={a.id}><strong>{a.text}</strong><span>{new Date(a.at).toLocaleString()}</span></div>)}</div></section></div></div>;
}
