import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import * as XLSX from '@keep-lts/xlsx';
import { Check, Download, FileSpreadsheet, FileText, Image, List, Loader2, MessageSquare, Paperclip, Plus, Send, Smartphone, Trash2, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';
import { useSessions } from '../hooks/use-sessions';
import { campaignJobsApi, campaignsApi, type CampaignButton, type CampaignList, type CampaignListRow, type CampaignMedia, type CampaignRecipient, type CampaignResult } from '../lib/api';
import { consumeTemplateHandoff, type MessageTemplate } from '../lib/template-store';
import '../styles/send-message.css';
import '../styles/send-media.css';
import '../styles/interactive-campaign.css';

type MessageType = 'text' | 'media' | 'media-text' | 'buttons' | 'list';
type RecipientRow = CampaignRecipient & { row: number; valid: boolean; error?: string };
type MediaDraft = CampaignMedia & { size: number; previewUrl?: string };
type ListSection = { title: string; rows: CampaignListRow[] };
const PHONE_HEADERS = ['phone', 'number', 'mobile', 'mobilenumber', 'whatsapp', 'whatsappnumber', 'contact', 'phonenumber'];
const MAX_RECIPIENTS = 250; const MAX_MEDIA_BYTES = 8 * 1024 * 1024; const MAX_BUTTONS = 3; const MAX_LIST_ROWS = 10;
const messageTypes: { id: MessageType; label: string; description: string; icon: typeof MessageSquare }[] = [
  { id: 'text', label: 'Text', description: 'Plain WhatsApp message', icon: MessageSquare },
  { id: 'media', label: 'Media', description: 'Image, video or document', icon: Paperclip },
  { id: 'media-text', label: 'Media + Text', description: 'Media with a caption', icon: Image },
  { id: 'buttons', label: 'Buttons', description: 'Interactive reply buttons', icon: Smartphone },
  { id: 'list', label: 'List', description: 'Interactive list message', icon: List },
];
function isOnline(session: { state?: string; status?: string }) { return ['open', 'connected', 'online'].includes(String(session.state || session.status || '').toLowerCase()); }
function normalizeHeader(value: unknown) { return String(value ?? '').trim().toLowerCase().replace(/[\s_-]+/g, ''); }
function normalizePhone(value: unknown) { return String(value ?? '').trim().replace(/[^0-9]/g, ''); }
function personalize(template: string, recipient?: CampaignRecipient) { return template.replace(/\{\{\s*(name|company|custom1|custom2)\s*\}\}/gi, (_, key) => String(recipient?.[key.toLowerCase() as keyof CampaignRecipient] ?? '')); }
function formatBytes(bytes: number) { return `${(bytes / 1024 / 1024).toFixed(2)} MB`; }
function mediaTypeFor(file: File): CampaignMedia['mediatype'] | null { if (file.type.startsWith('image/')) return 'image'; if (file.type.startsWith('video/')) return 'video'; if (file.type === 'application/pdf' || file.type.startsWith('text/') || file.type.includes('word') || file.type.includes('excel') || file.type.includes('powerpoint') || /\.(pdf|docx?|xlsx?|pptx?|txt)$/i.test(file.name)) return 'document'; return null; }
function readFileBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const result = String(reader.result || ''); const comma = result.indexOf(','); resolve(comma >= 0 ? result.slice(comma + 1) : result); }; reader.onerror = () => reject(new Error('Could not read the media file.')); reader.readAsDataURL(file); }); }
function parseRecipientSheet(data: ArrayBuffer): RecipientRow[] {
  const workbook = XLSX.read(data, { type: 'array' }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) throw new Error('The workbook does not contain a sheet.'); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: '' }); if (!rows.length) throw new Error('The spreadsheet is empty.');
  const headerMap = new Map<string, string>(); Object.keys(rows[0]).forEach((key) => headerMap.set(normalizeHeader(key), key)); const phoneHeader = PHONE_HEADERS.find((key) => headerMap.has(key)); if (!phoneHeader) throw new Error('A phone column is required. Use phone, number, mobile or whatsapp.'); const phoneKey = headerMap.get(phoneHeader)!; const getValue = (row: Record<string, unknown>, header: string) => { const key = headerMap.get(header); return key ? String(row[key] ?? '').trim() : ''; }; const seen = new Set<string>();
  return rows.map((row, index) => { const phone = normalizePhone(row[phoneKey]); let error = ''; if (!phone) error = 'Missing phone number'; else if (phone.length < 8 || phone.length > 15) error = 'Phone must contain 8–15 digits'; else if (seen.has(phone)) error = 'Duplicate phone number'; else seen.add(phone); return { row: index + 2, phone, name: getValue(row, 'name') || undefined, company: getValue(row, 'company') || undefined, custom1: getValue(row, 'custom1') || undefined, custom2: getValue(row, 'custom2') || undefined, valid: !error, error: error || undefined }; });
}
function downloadTemplate() { const rows = [{ phone: '919876543210', name: 'Rahul', company: 'Acme', custom1: 'Premium', custom2: 'Delhi' }, { phone: '919812345678', name: 'Priya', company: 'Beta Ltd', custom1: 'New', custom2: 'Mumbai' }]; const worksheet = XLSX.utils.json_to_sheet(rows); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, 'Recipients'); XLSX.writeFile(workbook, 'whatsapp-recipients-template.xlsx'); }

export function SendMessagePage() {
  const navigate = useNavigate();
  const { data: sessions = [], isLoading } = useSessions(); const connected = useMemo(() => sessions.filter(isOnline), [sessions]); const [instance, setInstance] = useState(''); const [type, setType] = useState<MessageType>('text'); const [draft, setDraft] = useState(''); const [recipients, setRecipients] = useState<RecipientRow[]>([]); const [fileName, setFileName] = useState(''); const [media, setMedia] = useState<MediaDraft | null>(null); const [isParsing, setIsParsing] = useState(false); const [isMediaLoading, setIsMediaLoading] = useState(false); const [isSending, setIsSending] = useState(false); const [result, setResult] = useState<CampaignResult | null>(null); const [campaignId, setCampaignId] = useState(''); const [campaignStatus, setCampaignStatus] = useState('');
  const [buttonItems, setButtonItems] = useState<CampaignButton[]>([{ type: 'reply', id: 'option_1', displayText: 'Option 1' }, { type: 'reply', id: 'option_2', displayText: 'Option 2' }]); const [buttonTitle, setButtonTitle] = useState('Choose an option'); const [buttonDescription, setButtonDescription] = useState('Hi {{name}}, please choose one of the options below.'); const [buttonFooter, setButtonFooter] = useState('Reply with your choice');
  const [listTitle, setListTitle] = useState('Choose an option'); const [listDescription, setListDescription] = useState('Hi {{name}}, please choose from the list below.'); const [listFooter, setListFooter] = useState('Reply with your choice'); const [listButtonText, setListButtonText] = useState('View options'); const [sections, setSections] = useState<ListSection[]>([{ title: 'Options', rows: [{ title: 'Option 1', description: 'First option', rowId: 'option_1' }, { title: 'Option 2', description: 'Second option', rowId: 'option_2' }] }]);
  const recipientFileRef = useRef<HTMLInputElement>(null); const mediaFileRef = useRef<HTMLInputElement>(null); const selectedInstance = connected.some((session) => session.instanceName === instance) ? instance : connected[0]?.instanceName || ''; const validRecipients = useMemo(() => recipients.filter((recipient) => recipient.valid), [recipients]); const invalidRecipients = recipients.length - validRecipients.length; const sampleRecipient = validRecipients[0]; const isMediaMode = type === 'media' || type === 'media-text'; const interactiveMode = type === 'buttons' || type === 'list'; const totalRows = sections.reduce((total, section) => total + section.rows.length, 0); const previewTitle = personalize(type === 'buttons' ? buttonTitle : listTitle, sampleRecipient); const previewDescription = personalize(type === 'buttons' ? buttonDescription : listDescription, sampleRecipient);

  const applyTemplate = (template: MessageTemplate) => {
    setType(template.type);
    setDraft(template.type === 'text' || template.type === 'media-text' ? template.text || '' : '');
    if (template.type === 'buttons') {
      setButtonTitle(template.title || ''); setButtonDescription(template.description || ''); setButtonFooter(template.footer || '');
      setButtonItems((template.buttons || []).map((button) => ({ type: 'reply', id: button.id, displayText: button.displayText })));
    }
    if (template.type === 'list') {
      setListTitle(template.title || ''); setListDescription(template.description || ''); setListFooter(template.footer || ''); setListButtonText(template.buttonText || '');
      setSections((template.sections || []).map((section) => ({ title: section.title, rows: section.rows.map((row) => ({ rowId: row.rowId, title: row.title, description: row.description })) })));
    }
    setResult(null);
    toast.success(`Loaded template: ${template.name}`);
  };

  useEffect(() => {
    const template = consumeTemplateHandoff();
    if (template) applyTemplate(template);
  }, []);

  const handleRecipientFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setIsParsing(true); setResult(null); try { if (!/\.(xlsx|xls|csv)$/i.test(file.name)) throw new Error('Please upload an XLSX, XLS or CSV file.'); const rows = parseRecipientSheet(await file.arrayBuffer()); if (rows.length > MAX_RECIPIENTS) throw new Error(`This campaign supports up to ${MAX_RECIPIENTS} spreadsheet rows.`); setRecipients(rows); setFileName(file.name); toast.success(`Imported ${rows.length} recipient rows`); } catch (error) { setRecipients([]); setFileName(''); toast.error(error instanceof Error ? error.message : 'Could not read the spreadsheet.'); } finally { setIsParsing(false); } };
  const handleMediaFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setIsMediaLoading(true); setResult(null); try { if (file.size > MAX_MEDIA_BYTES) throw new Error('Media must be 8 MB or smaller.'); const mediatype = mediaTypeFor(file); if (!mediatype) throw new Error('Supported media: images, videos, PDF and common office/text documents.'); const base64 = await readFileBase64(file); const next: MediaDraft = { base64, mediatype, mimetype: file.type || 'application/octet-stream', fileName: file.name, size: file.size }; if (file.type.startsWith('image/') || file.type.startsWith('video/')) next.previewUrl = URL.createObjectURL(file); setMedia(next); toast.success(`${file.name} attached`); } catch (error) { setMedia(null); toast.error(error instanceof Error ? error.message : 'Could not load media.'); } finally { setIsMediaLoading(false); } };
  const clearMedia = () => { if (media?.previewUrl) URL.revokeObjectURL(media.previewUrl); setMedia(null); setResult(null); }; const clearRecipients = () => { setRecipients([]); setFileName(''); setResult(null); }; const updateButton = (index: number, patch: Partial<CampaignButton>) => setButtonItems((items) => items.map((item, i) => i === index ? { ...item, ...patch } : item)); const updateRow = (sectionIndex: number, rowIndex: number, patch: Partial<CampaignListRow>) => setSections((items) => items.map((section, i) => i === sectionIndex ? { ...section, rows: section.rows.map((row, j) => j === rowIndex ? { ...row, ...patch } : row) } : section)); const addRow = (sectionIndex: number) => { if (totalRows >= MAX_LIST_ROWS) return; setSections((items) => items.map((section, i) => i === sectionIndex ? { ...section, rows: [...section.rows, { title: `Option ${section.rows.length + 1}`, description: '', rowId: `option_${totalRows + 1}` }] } : section)); }; const addSection = () => { if (totalRows >= MAX_LIST_ROWS || sections.length >= 5) return; setSections((items) => [...items, { title: `Section ${items.length + 1}`, rows: [{ title: 'New option', description: '', rowId: `option_${totalRows + 1}` }] }]); };
  const sendCampaign = async () => {
    if (!selectedInstance) return toast.error('Select a connected WhatsApp instance.'); if (!validRecipients.length) return toast.error('Import at least one valid recipient.'); if (isMediaMode && !media) return toast.error('Attach an image, video or document first.'); if (type === 'text' && !draft.trim()) return toast.error('Write a message first.'); if (type === 'media-text' && !draft.trim()) return toast.error('Write a caption first.');
    if (type === 'buttons') { if (!buttonTitle.trim()) return toast.error('Enter a button title.'); if (!buttonItems.length || buttonItems.length > MAX_BUTTONS) return toast.error('Use 1–3 buttons.'); const ids = buttonItems.map((button) => button.id?.trim()).filter(Boolean) as string[]; const labels = buttonItems.map((button) => button.displayText.trim()).filter(Boolean); if (ids.length !== buttonItems.length || labels.length !== buttonItems.length) return toast.error('Every button needs an ID and display text.'); if (new Set(ids).size !== ids.length || new Set(labels).size !== labels.length) return toast.error('Button IDs and display text must be unique.'); }
    if (type === 'list') { if (!listTitle.trim() || !listButtonText.trim()) return toast.error('Enter a list title and menu button text.'); if (!totalRows || totalRows > MAX_LIST_ROWS) return toast.error(`Use 1–${MAX_LIST_ROWS} list rows.`); const ids = sections.flatMap((section) => section.rows.map((row) => row.rowId.trim())); if (ids.some((id) => !id) || new Set(ids).size !== ids.length) return toast.error('List row IDs must be present and unique.'); if (sections.some((section) => !section.title.trim() || section.rows.some((row) => !row.title.trim()))) return toast.error('Every section and row needs a title.'); }
    setIsSending(true); setResult(null); setCampaignId(''); setCampaignStatus('queued');
    try {
      const cleanRecipients = validRecipients.map(({ row: _row, valid: _valid, error: _error, ...recipient }) => recipient);
      const payload: Record<string, unknown> = type === 'text'
        ? { text: draft.trim() }
        : isMediaMode
          ? { media: media!, caption: type === 'media-text' ? draft.trim() : '' }
          : type === 'buttons'
            ? { title: buttonTitle.trim(), description: buttonDescription.trim(), footer: buttonFooter.trim(), buttons: buttonItems.map((button) => ({ ...button, id: button.id?.trim(), displayText: button.displayText.trim() })) }
            : { title: listTitle.trim(), description: listDescription.trim(), footerText: listFooter.trim(), buttonText: listButtonText.trim(), sections: sections.map((section) => ({ title: section.title.trim(), rows: section.rows.map((row) => ({ rowId: row.rowId.trim(), title: row.title.trim(), description: row.description?.trim() })) })) };
      const job = await campaignJobsApi.create(`${type === 'media-text' ? 'Media + Text' : type.charAt(0).toUpperCase() + type.slice(1)} campaign`, type, selectedInstance, cleanRecipients, payload, 1500);
      setCampaignId(job.id);
      setCampaignStatus(job.status);
      setResult(job);
      if (job.status === 'queued' || job.status === 'running') {
        const poll = async () => {
          try {
            const current = await campaignJobsApi.get(job.id);
            setCampaignStatus(current.status);
            setResult(current);
            if (current.status === 'completed' || current.status === 'failed') {
              setIsSending(false);
              if (current.failed) toast.warning(`${current.sent} sent, ${current.failed} failed`);
              else if (current.status === 'completed') toast.success(`${current.sent} messages sent`);
              return;
            }
            window.setTimeout(poll, 1000);
          } catch (error) {
            setIsSending(false);
            toast.error(error instanceof Error ? error.message : 'Could not update campaign status.');
          }
        };
        window.setTimeout(poll, 700);
      } else setIsSending(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Campaign could not be queued.');
      setIsSending(false);
    }
  };
  return <div className="sendPage"><section className="hero sendHero"><div><p className="eyebrow">CAMPAIGNS</p><h1>Send Message</h1><p>One campaign builder for text, media, reply buttons and list messages.</p></div><div className="sendStatus"><i /> {interactiveMode ? 'Interactive Campaigns' : 'WhatsApp Campaigns'}</div></section>
    {!connected.length && !isLoading ? <section className="sendEmpty"><div className="sendEmptyIcon"><Smartphone size={24} /></div><h2>No connected session</h2><p>Connect a WhatsApp session first. Only connected sessions can be used for campaigns.</p></section> : <div className="sendLayout"><section className="sendCard">
      <div className="sendSection"><div className="sendSectionHead"><div className="stepNumber">1</div><div><h2>WhatsApp instance</h2><p>Select the connected number that will send the campaign.</p></div></div><div className="instanceGrid">{connected.map((session) => { const active = selectedInstance === session.instanceName; return <button type="button" key={session.instanceName} className={`instanceOption ${active ? 'active' : ''}`} onClick={() => setInstance(session.instanceName || '')}><div className="instanceIcon"><Smartphone size={18} /></div><div className="instanceCopy"><strong>{session.profileName || session.instanceName}</strong><span>{session.number ? `+${String(session.number).replace(/^\+/, '')}` : session.instanceName}</span></div><span className="onlineBadge"><i /> Connected</span>{active && <span className="selectedCheck"><Check size={13} /></span>}</button>; })}</div></div>
      <div className="sendDivider" /><div className="sendSection"><div className="sendSectionHead"><div className="stepNumber">2</div><div><h2>Recipients</h2><p>Required: <b>phone</b>. Optional: name, company, custom1, custom2.</p></div></div><input ref={recipientFileRef} className="hiddenFileInput" type="file" accept=".xlsx,.xls,.csv" onChange={handleRecipientFile} /><div className="uploadRow"><button type="button" className="uploadDrop" onClick={() => recipientFileRef.current?.click()} disabled={isParsing}><span className="uploadIcon">{isParsing ? <Loader2 size={19} className="spin" /> : <Upload size={19} />}</span><span><strong>{isParsing ? 'Reading spreadsheet…' : 'Upload recipient XLSX'}</strong><small>XLSX, XLS or CSV · up to {MAX_RECIPIENTS} rows</small></span></button><button type="button" className="secondary templateBtn" onClick={downloadTemplate}><Download size={14} /> Template</button></div>{recipients.length > 0 && <><div className="recipientStats"><div><strong>{recipients.length}</strong><span>Rows</span></div><div className="valid"><strong>{validRecipients.length}</strong><span>Valid</span></div><div className={invalidRecipients ? 'invalid' : ''}><strong>{invalidRecipients}</strong><span>Invalid</span></div><div className="fileName"><FileSpreadsheet size={14} /><span>{fileName}</span><button type="button" onClick={clearRecipients}><X size={13} /></button></div></div><div className="recipientTableWrap"><table className="recipientTable"><thead><tr><th>Row</th><th>Phone</th><th>Name</th><th>Company</th><th>Status</th></tr></thead><tbody>{recipients.slice(0, 8).map((recipient) => <tr key={recipient.row} className={!recipient.valid ? 'invalidRow' : ''}><td>{recipient.row}</td><td>{recipient.phone || '—'}</td><td>{recipient.name || '—'}</td><td>{recipient.company || '—'}</td><td><span className={`rowStatus ${recipient.valid ? 'ok' : 'bad'}`}>{recipient.valid ? 'Valid' : recipient.error}</span></td></tr>)}</tbody></table>{recipients.length > 8 && <div className="tableMore">Showing first 8 rows · {recipients.length - 8} more will be included.</div>}</div></>}</div>
      <div className="sendDivider" /><div className="sendSection"><div className="sendSectionHead"><div className="stepNumber">3</div><div><h2>Message type</h2><p>Choose the message format for this campaign.</p></div><button type="button" className="secondary templateBtn" onClick={() => navigate('/templates')}><FileText size={14} /> Templates</button></div><div className="messageTypeGrid">{messageTypes.map(({ id, label, description, icon: Icon }) => { const active = type === id; return <button type="button" key={id} className={`messageTypeOption ${active ? 'active' : ''}`} onClick={() => { setType(id); setResult(null); }}><span className="typeIcon"><Icon size={17} /></span><span className="typeCopy"><strong>{label}</strong><small>{description}</small></span>{active && <span className="selectedCheck"><Check size={13} /></span>}</button>; })}</div></div>
      {!interactiveMode && <><div className="sendDivider" /><div className="sendSection"><div className="sendSectionHead"><div className="stepNumber">4</div><div><h2>{isMediaMode ? 'Media' : 'Message'}</h2><p>{isMediaMode ? 'Attach one image, video or document.' : 'Use {{name}}, {{company}}, {{custom1}} or {{custom2}} for personalization.'}</p></div></div>{isMediaMode && <><input ref={mediaFileRef} className="hiddenFileInput" type="file" accept="image/*,video/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt" onChange={handleMediaFile} />{!media ? <button type="button" className="mediaDrop" onClick={() => mediaFileRef.current?.click()} disabled={isMediaLoading}><Paperclip size={20} /><span><strong>{isMediaLoading ? 'Reading media…' : 'Choose media'}</strong><small>Images, videos, PDF and common documents · max 8 MB</small></span></button> : <div className="mediaAttached">{media.previewUrl ? <img src={media.previewUrl} alt={media.fileName} /> : <div className="mediaFileIcon"><FileText size={24} /></div>}<div><strong>{media.fileName}</strong><small>{media.mediatype} · {formatBytes(media.size)}</small></div><button type="button" onClick={clearMedia}><X size={15} /></button></div>}</>}{(!isMediaMode || type === 'media-text') && <label className="composerLabel">{type === 'media-text' ? 'Caption' : 'Message'}<textarea value={draft} onChange={(event) => setDraft(event.target.value)} rows={7} placeholder={type === 'media-text' ? 'Hi {{name}}, here is your update.' : 'Type your WhatsApp message…'} /></label>}</div></>}
      {type === 'buttons' && <><div className="sendDivider" /><div className="sendSection interactiveSection"><div className="sendSectionHead"><div className="stepNumber">4</div><div><h2>Reply buttons</h2><p>1–3 unique reply buttons. Personalization works in title, description and footer.</p></div></div><div className="fieldGrid"><label>Title<input value={buttonTitle} onChange={(event) => setButtonTitle(event.target.value)} /></label><label>Description<textarea value={buttonDescription} onChange={(event) => setButtonDescription(event.target.value)} rows={3} /></label><label>Footer<input value={buttonFooter} onChange={(event) => setButtonFooter(event.target.value)} /></label></div><div className="itemList">{buttonItems.map((button, index) => <div className="itemRow" key={`${button.id}-${index}`}><input value={button.id || ''} onChange={(event) => updateButton(index, { id: event.target.value })} placeholder="button_id" /><input value={button.displayText} onChange={(event) => updateButton(index, { displayText: event.target.value })} placeholder="Display text" /><button type="button" disabled={buttonItems.length <= 1} onClick={() => setButtonItems((items) => items.filter((_, i) => i !== index))}><Trash2 size={14} /></button></div>)}</div>{buttonItems.length < MAX_BUTTONS && <button type="button" className="addButton" onClick={() => setButtonItems((items) => [...items, { type: 'reply', id: `option_${items.length + 1}`, displayText: `Option ${items.length + 1}` }])}><Plus size={14} /> Add button</button>}</div></>}
      {type === 'list' && <><div className="sendDivider" /><div className="sendSection interactiveSection"><div className="sendSectionHead"><div className="stepNumber">4</div><div><h2>List message</h2><p>Up to 10 rows across up to 5 sections. Row IDs must be unique.</p></div></div><div className="fieldGrid"><label>Title<input value={listTitle} onChange={(event) => setListTitle(event.target.value)} /></label><label>Description<textarea value={listDescription} onChange={(event) => setListDescription(event.target.value)} rows={3} /></label><label>Footer<input value={listFooter} onChange={(event) => setListFooter(event.target.value)} /></label><label>Menu button text<input value={listButtonText} onChange={(event) => setListButtonText(event.target.value)} /></label></div>{sections.map((section, sectionIndex) => <div className="listEditor" key={sectionIndex}><div className="listSectionTitle"><input value={section.title} onChange={(event) => setSections((items) => items.map((item, i) => i === sectionIndex ? { ...item, title: event.target.value } : item))} placeholder="Section title" /><button type="button" disabled={sections.length <= 1} onClick={() => setSections((items) => items.filter((_, i) => i !== sectionIndex))}><Trash2 size={14} /></button></div>{section.rows.map((row, rowIndex) => <div className="itemRow" key={rowIndex}><input value={row.rowId} onChange={(event) => updateRow(sectionIndex, rowIndex, { rowId: event.target.value })} placeholder="row_id" /><input value={row.title} onChange={(event) => updateRow(sectionIndex, rowIndex, { title: event.target.value })} placeholder="Row title" /><input value={row.description || ''} onChange={(event) => updateRow(sectionIndex, rowIndex, { description: event.target.value })} placeholder="Description" /><button type="button" disabled={section.rows.length <= 1} onClick={() => setSections((items) => items.map((item, i) => i === sectionIndex ? { ...item, rows: item.rows.filter((_, j) => j !== rowIndex) } : item))}><Trash2 size={14} /></button></div>)}{totalRows < MAX_LIST_ROWS && <button type="button" className="addButton" onClick={() => addRow(sectionIndex)}><Plus size={14} /> Add row</button>}</div>)}{sections.length < 5 && totalRows < MAX_LIST_ROWS && <button type="button" className="addButton" onClick={addSection}><Plus size={14} /> Add section</button>}</div></>}
      {result && <div className="campaignResult"><strong>{campaignStatus === 'queued' ? 'Campaign queued' : campaignStatus === 'running' ? 'Campaign sending' : campaignStatus === 'completed' ? 'Campaign finished' : 'Campaign failed'}</strong><span>{result.sent} sent · {result.failed} failed · {Math.max(0, result.total - result.sent - result.failed)} remaining{campaignId ? ` · ${campaignId}` : ''}</span></div>}
    </section><aside className="sendAside"><div className="sendPreview"><div className="previewHeader"><MessageSquare size={14} /><span>WhatsApp preview</span></div><div className="previewBubble">{interactiveMode ? <><strong>{previewTitle || 'Choose an option'}</strong><p>{previewDescription}</p>{type === 'buttons' ? <div className="previewButtons">{buttonItems.map((button) => <span key={button.id}>{button.displayText || 'Button'}</span>)}</div> : <><div className="previewListButton">{listButtonText || 'View options'}</div><div className="previewRows">{sections.flatMap((section) => section.rows).slice(0, 4).map((row) => <div key={row.rowId}><strong>{personalize(row.title, sampleRecipient)}</strong><small>{personalize(row.description || '', sampleRecipient)}</small></div>)}</div></>}<small className="previewFooter">{personalize(type === 'buttons' ? buttonFooter : listFooter, sampleRecipient)}</small></> : <><p>{personalize(draft, sampleRecipient) || 'Your message preview will appear here.'}</p>{media?.previewUrl && <img src={media.previewUrl} alt="Media preview" />}{media && !media.previewUrl && <div className="previewDocument"><FileText size={17} /> {media.fileName}</div>}</>}</div></div><div className="sendActions"><div><strong>{validRecipients.length}</strong><span>valid recipients</span></div><button type="button" onClick={sendCampaign} disabled={isSending || !selectedInstance || !validRecipients.length}>{isSending ? <><Loader2 size={15} className="spin" /> Sending…</> : <><Send size={15} /> Send campaign</>}</button><p>250-recipient limit · 1.5 sec pacing · use only with opted-in recipients.</p></div></aside></div>}
  </div>;
}
