import { useEffect, useState } from 'react';
import { Pencil, Plus, ShieldCheck, Trash2, Users } from 'lucide-react';
import { toast } from 'sonner';
import { workspaceApi, type WorkspaceMember } from '../lib/api';
import '../styles/workspace.css';

const defaultPermissions={dashboard:true,leadsView:true,leadsEdit:false,inboxReply:true,inboxAssign:false,templatesUse:true,templatesManage:false,campaigns:false,automations:false,analytics:false,settings:false};
const keys=Object.keys(defaultPermissions);
export function TeamPage(){
 const [members,setMembers]=useState<WorkspaceMember[]>([]),[editing,setEditing]=useState<WorkspaceMember|null>(null),[open,setOpen]=useState(false);
 const load=async()=>{try{setMembers(await workspaceApi.members())}catch(e){toast.error(e instanceof Error?e.message:'Could not load team.')}};useEffect(()=>{void load()},[]);
 const save=async()=>{if(!editing?.name.trim())return toast.error('Member name is required.');try{if(editing.id)await workspaceApi.updateMember(editing.id,editing);else await workspaceApi.createMember(editing);toast.success(editing.id?'Member updated':'Member added');setOpen(false);setEditing(null);await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not save member.')}};
 return <div className="workspacePage"><section className="hero"><div><p className="eyebrow">WORKSPACE</p><h1>Team management</h1><p>Add members and manage who can access the workspace.</p></div><button className="primary" onClick={()=>{setEditing({id:'',name:'',email:'',jobTitle:'',status:'active',permissions:{...defaultPermissions},createdAt:''});setOpen(true)}}><Plus size={14}/> Add member</button></section>{!members.length?<div className="empty"><Users size={24}/><h3>No team members yet</h3><p>Add your first workspace member.</p></div>:<div className="tableWrap"><table><thead><tr><th>Member</th><th>Title</th><th>Status</th><th>Actions</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><strong>{m.name}</strong><span>{m.email}</span></td><td>{m.jobTitle||'—'}</td><td><span className={`status ${m.status}`}>{m.status}</span></td><td><div className="tableActions"><button onClick={()=>{setEditing(m);setOpen(true)}}><Pencil size={13}/></button><button onClick={()=>{window.location.href='/permissions?member='+encodeURIComponent(m.id)}}><ShieldCheck size={13}/></button><button className="danger" onClick={async()=>{await workspaceApi.removeMember(m.id);await load()}}><Trash2 size={13}/></button></div></td></tr>)}</tbody></table></div>}{open&&editing&&<div className="modalBackdrop"><section className="modal"><div className="modalHead"><strong>{editing.id?'Edit member':'Add member'}</strong><button className="iconBtn" onClick={()=>setOpen(false)}>×</button></div><div className="form"><label>Name<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Email<input value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><label>Job title<input value={editing.jobTitle} onChange={e=>setEditing({...editing,jobTitle:e.target.value})}/></label><label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as WorkspaceMember['status']})}><option>active</option><option>invited</option><option>suspended</option></select></label></div><div className="cardActions"><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" onClick={()=>void save()}>Save</button></div></section></div>}</div>;
}

export function PermissionsPage(){
 const [members,setMembers]=useState<WorkspaceMember[]>([]),[selected,setSelected]=useState<string>('');const [permissions,setPermissions]=useState<Record<string,boolean>>({});
 const load=async()=>{try{const m=await workspaceApi.members();setMembers(m);const current=m.find(x=>x.id===selected)||m[0];if(current){setSelected(current.id);setPermissions(current.permissions)}}catch(e){toast.error(e instanceof Error?e.message:'Could not load permissions.')}};useEffect(()=>{void load()},[]);
 const choose=(id:string)=>{const m=members.find(x=>x.id===id);if(m){setSelected(id);setPermissions(m.permissions)}};
 const save=async()=>{try{await workspaceApi.permissions(selected,permissions);toast.success('Permissions saved')}catch(e){toast.error(e instanceof Error?e.message:'Could not save permissions.')}};
 return <div className="workspacePage"><section className="hero"><div><p className="eyebrow">ACCESS CONTROL</p><h1>Permission management</h1><p>Control access to CRM, inbox, templates, campaigns and analytics.</p></div></section><div className="permissionLayout"><div className="memberPicker">{members.map(m=><button key={m.id} className={m.id===selected?'active':''} onClick={()=>choose(m.id)}>{m.name}<span>{m.jobTitle||m.status}</span></button>)}</div><section className="card"><div className="sectionHeading"><h2>Permissions</h2><button className="primary" onClick={()=>void save()}>Save changes</button></div>{keys.map(k=><label className="permissionRow" key={k}><span>{k}</span><input type="checkbox" checked={!!permissions[k]} onChange={e=>setPermissions({...permissions,[k]:e.target.checked})}/></label>)}</section></div></div>
}

export function SettingsPage(){
 const [s,setS]=useState<any>({workspaceName:'Prachar Studio',ownerName:'',ownerEmail:'',whatsappNumber:'',timezone:'Asia/Kolkata',notifyNewLead:true,notifyNewMessage:true});
 useEffect(()=>{void workspaceApi.settings().then(setS).catch(()=>undefined)},[]);
 const save=(patch:any)=>{const next={...s,...patch};setS(next);void workspaceApi.updateSettings(next).then(()=>toast.success('Settings saved')).catch(e=>toast.error(e instanceof Error?e.message:'Could not save settings.'))};
 return <div className="workspacePage"><section className="hero"><div><p className="eyebrow">SETTINGS</p><h1>Settings</h1><p>Manage workspace identity, WhatsApp details and notifications.</p></div></section><div className="settingsGrid"><section className="card"><h2>Business profile</h2>{[['workspaceName','Workspace name'],['ownerName','Owner name'],['ownerEmail','Owner email']].map(([k,l])=><label className="formField" key={k}>{l}<input value={s[k]||''} onChange={e=>setS({...s,[k]:e.target.value})} onBlur={()=>save({[k]:s[k]})}/></label>)}</section><section className="card"><h2>WhatsApp & notifications</h2><label className="formField">WhatsApp business number<input value={s.whatsappNumber||''} onChange={e=>setS({...s,whatsappNumber:e.target.value})} onBlur={()=>save({whatsappNumber:s.whatsappNumber})}/></label><label className="formField">Timezone<input value={s.timezone||''} onChange={e=>setS({...s,timezone:e.target.value})} onBlur={()=>save({timezone:s.timezone})}/></label><label className="toggle"><span>Notify new leads</span><input type="checkbox" checked={s.notifyNewLead!==false} onChange={e=>save({notifyNewLead:e.target.checked})}/></label><label className="toggle"><span>Notify new messages</span><input type="checkbox" checked={s.notifyNewMessage!==false} onChange={e=>save({notifyNewMessage:e.target.checked})}/></label></section></div></div>
}
