import { Router } from 'express';
import { pool } from '../services/db.js';
export const automationRouter=Router();
const clean=v=>String(v??'').trim();
const defaultTrigger={id:'trigger',type:'trigger',label:'Trigger',config:{event:'lead_created'}};
const mapRow=r=>({id:r.id,name:r.name,status:r.status,nodes:r.nodes||[],createdAt:r.created_at});
async function get(id){const a=await pool.query('SELECT * FROM automations WHERE id=$1',[id]);if(!a.rows[0])return null;const n=await pool.query('SELECT id,type,label,config FROM automation_nodes WHERE automation_id=$1 ORDER BY node_index',[id]);return mapRow({...a.rows[0],nodes:n.rows});}
const makeId=()=> 'auto_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
automationRouter.get('/',async(_req,res,next)=>{try{const {rows}=await pool.query('SELECT * FROM automations ORDER BY created_at DESC');const out=[];for(const r of rows)out.push(await get(r.id));res.json(out)}catch(e){next(e)}});
automationRouter.post('/',async(req,res,next)=>{try{const name=clean(req.body?.name);if(!name)return res.status(400).json({ok:false,message:'Automation name is required.'});const aid=makeId();await pool.query('INSERT INTO automations(id,name,status) VALUES($1,$2,$3)',[aid,name,'draft']);await pool.query('INSERT INTO automation_nodes(id,automation_id,node_index,type,label,config) VALUES($1,$2,0,$3,$4,$5::jsonb)',[makeId(),aid,'trigger','Trigger',JSON.stringify({event:'lead_created'})]);res.status(201).json(await get(aid))}catch(e){next(e)}});
automationRouter.put('/:id',async(req,res,next)=>{const client=await pool.connect();try{const current=await get(req.params.id);if(!current)return res.status(404).json({ok:false,message:'Automation not found.'});await client.query('BEGIN');if(req.body?.name!==undefined||req.body?.status!==undefined)await client.query('UPDATE automations SET name=COALESCE($2,name),status=COALESCE($3,status),updated_at=NOW() WHERE id=$1',[req.params.id,req.body.name,req.body.status]);if(Array.isArray(req.body?.nodes)){await client.query('DELETE FROM automation_nodes WHERE automation_id=$1',[req.params.id]);for(let i=0;i<req.body.nodes.length;i++){const n=req.body.nodes[i];await client.query('INSERT INTO automation_nodes(id,automation_id,node_index,type,label,config) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[n.id||makeId(),req.params.id,i,n.type,n.label||n.type,JSON.stringify(n.config||{})])}}await client.query('COMMIT');res.json(await get(req.params.id))}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
automationRouter.delete('/:id',async(req,res,next)=>{try{const r=await pool.query('DELETE FROM automations WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({ok:false,message:'Automation not found.'});res.status(204).end()}catch(e){next(e)}});
