import { Router } from 'express';
import { pool } from '../services/db.js';
import crypto from 'node:crypto';
import { authUser, requireOwner, requirePermission } from './auth.routes.js';

export const workspaceRouter=Router();
workspaceRouter.use(authUser);
const defaults={dashboard:true,leadsView:true,leadsEdit:false,inboxReply:true,inboxAssign:false,templatesUse:true,templatesManage:false,campaigns:false,automations:false,analytics:false,settings:false};
const makeId=(p)=>p+'_'+Date.now().toString(36)+'_'+crypto.randomBytes(5).toString('hex');
const map=(r)=>({id:r.id,name:r.name,email:r.email,jobTitle:r.job_title,status:r.status,permissions:r.permissions||defaults,createdAt:r.created_at});
workspaceRouter.get('/members',requireOwner,async(_q,res,next)=>{try{const {rows}=await pool.query('SELECT id,name,email,job_title,status,permissions,created_at FROM members ORDER BY created_at DESC');res.json(rows.map(map))}catch(e){next(e)}});
workspaceRouter.post('/members',requireOwner,async(req,res,next)=>{const c=await pool.connect();try{const b=req.body||{};if(!String(b.name||'').trim())return res.status(400).json({ok:false,message:'Member name is required.'});const mid=makeId('mem');await c.query('BEGIN');await c.query('INSERT INTO members(id,name,email,job_title,status,permissions) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[mid,String(b.name).trim(),String(b.email||'').trim(),String(b.jobTitle||'').trim(),['active','invited','suspended'].includes(b.status)?b.status:'active',JSON.stringify({...defaults,...(b.permissions||{})})]);const uid=makeId('user');const email=String(b.email||'').trim().toLowerCase();if(email)await c.query('INSERT INTO app_users(id,member_id,email,password_hash,role,status) VALUES($1,$2,$3,$4,$5,$6)',[uid,mid,email,crypto.createHash('sha256').update(String(b.password||crypto.randomBytes(12).toString('hex'))).digest('hex'),'member','active']);await c.query('COMMIT');const r=await pool.query('SELECT * FROM members WHERE id=$1',[mid]);res.status(201).json(map(r.rows[0]));}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});
workspaceRouter.put('/members/:id',requireOwner,async(req,res,next)=>{try{const r=await pool.query('UPDATE members SET name=COALESCE($2,name),email=COALESCE($3,email),job_title=COALESCE($4,job_title),status=COALESCE($5,status),permissions=COALESCE($6::jsonb,permissions),updated_at=NOW() WHERE id=$1 RETURNING *',[req.params.id,req.body?.name,req.body?.email,req.body?.jobTitle,req.body?.status,req.body?.permissions?JSON.stringify(req.body.permissions):null]);if(!r.rows[0])return res.status(404).json({ok:false,message:'Member not found.'});res.json(map(r.rows[0]))}catch(e){next(e)}});
workspaceRouter.delete('/members/:id',requireOwner,async(req,res,next)=>{try{const r=await pool.query('DELETE FROM members WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({ok:false,message:'Member not found.'});await pool.query('DELETE FROM app_users WHERE member_id=$1',[req.params.id]);res.status(204).end()}catch(e){next(e)}});
workspaceRouter.put('/members/:id/permissions',requireOwner,async(req,res,next)=>{try{const p={...defaults,...Object.fromEntries(Object.entries(req.body?.permissions||{}).filter(([k,v])=>k in defaults&&typeof v==='boolean'))};const r=await pool.query('UPDATE members SET permissions=$2::jsonb,updated_at=NOW() WHERE id=$1 RETURNING permissions',[req.params.id,JSON.stringify(p)]);if(!r.rows[0])return res.status(404).json({ok:false,message:'Member not found.'});res.json(p)}catch(e){next(e)}});
workspaceRouter.get('/settings',requirePermission('settings'),async(_q,res,next)=>{try{const {rows}=await pool.query('SELECT key,value FROM workspace_settings');res.json(Object.fromEntries(rows.map(r=>[r.key,r.value])))}catch(e){next(e)}});
workspaceRouter.put('/settings',requirePermission('settings'),async(req,res,next)=>{try{for(const [k,v] of Object.entries(req.body||{}))await pool.query('INSERT INTO workspace_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[k,String(v)]);const {rows}=await pool.query('SELECT key,value FROM workspace_settings');res.json(Object.fromEntries(rows.map(r=>[r.key,r.value])))}catch(e){next(e)}});
