import "dotenv/config";

import crypto from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import axios from "axios";

const app = express();

const port = Number(process.env.PORT || 3000);

const evolutionUrl = String(process.env.EVOLUTION_API_URL || "").replace(
  /\/+$/,
  "",
);

const evolutionKey = String(process.env.EVOLUTION_API_KEY || "").trim();

const clientOrigin = process.env.CLIENT_ORIGIN || "http://localhost:5173";

if (!evolutionUrl || !evolutionKey) {
  console.warn(
    "Missing EVOLUTION_API_URL or EVOLUTION_API_KEY. Configure server/.env before using the manager.",
  );
}

app.use(helmet());

app.use(
  cors({
    origin: clientOrigin === "*" ? true : clientOrigin,
  }),
);

app.use(express.json({ limit: "1mb" }));

app.use(morgan("tiny"));

/**
 * Evolution API client
 *
 * Evolution API v2 expects the global API key
 * in the "apikey" header.
 */
const evo = axios.create({
  baseURL: evolutionUrl,
  timeout: 15000,
  headers: {
    "Content-Type": "application/json",
    apikey: evolutionKey,
  },
});

/**
 * Store instance tokens generated by this manager.
 *
 * This is in-memory, so tokens are lost when the server restarts.
 * Evolution itself remains the source of truth for the instances.
 */
const tokens = new Map();

/**
 * Evolution instance-name validation.
 */
const instanceNamePattern = /^[a-z0-9](?:[a-z0-9_-]{0,62}[a-z0-9])?$/;

/**
 * Convert Evolution/API errors into a useful message.
 */
function getErrorMessage(error) {
  const data = error?.response?.data;

  if (Array.isArray(data?.response?.message)) {
    return data.response.message.join(", ");
  }

  if (Array.isArray(data?.message)) {
    return data.message.join(", ");
  }

  if (typeof data?.message === "string") {
    return data.message;
  }

  if (typeof data === "string") {
    return data;
  }

  return error?.message || "Evolution API request failed";
}

/**
 * Return a consistent error response.
 */
function sendEvolutionError(res, error) {
  const status = error?.response?.status || 502;

  console.error(
    "Evolution API error:",
    JSON.stringify(
      {
        status,
        data: error?.response?.data,
        message: error?.message,
      },
      null,
      2,
    ),
  );

  return res.status(status).json({
    message: getErrorMessage(error),
    evolution: error?.response?.data,
  });
}

/**
 * Make an Evolution API request.
 */
async function evolutionRequest(config) {
  return evo.request(config);
}

/**
 * Fetch all Evolution instances.
 */
async function fetchInstances() {
  const { data } = await evo.get("/instance/fetchInstances");

  if (Array.isArray(data)) {
    return data;
  }

  if (Array.isArray(data?.instances)) {
    return data.instances;
  }

  return data ? [data] : [];
}

/**
 * Normalize an Evolution instance into the format
 * expected by the frontend.
 */
function normalizeInstance(item) {
  const instance = item?.instance || item;

  const instanceName =
    instance?.instanceName || item?.instanceName || item?.name;

  return {
    instanceName,

    status: instance?.status || item?.status,

    state:
      instance?.connectionStatus?.state ||
      item?.connectionStatus?.state ||
      instance?.state ||
      item?.state,

    ownerJid: instance?.owner || item?.owner,

    profileName: instance?.profileName || item?.profileName,

    number: instance?.number || item?.number,

    tokenKnown: instanceName ? tokens.has(instanceName) : false,

    raw: item,
  };
}

/* =========================================================
   HEALTH
   ========================================================= */

app.get("/api/health", async (_req, res) => {
  if (!evolutionUrl || !evolutionKey) {
    return res.status(503).json({
      ok: false,
      message: "Evolution API is not configured",
    });
  }

  try {
    await evo.get("/");

    return res.json({
      ok: true,
      evolutionApi: evolutionUrl,
    });
  } catch (error) {
    return res.status(502).json({
      ok: false,
      evolutionApi: evolutionUrl,
      message: getErrorMessage(error),
    });
  }
});

/* =========================================================
   LIST SESSIONS
   ========================================================= */

app.get("/api/sessions", async (_req, res) => {
  try {
    const instances = await fetchInstances();

    return res.json(
      instances.map(normalizeInstance).filter((item) => item.instanceName),
    );
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   CREATE SESSION
   ========================================================= */

app.post("/api/sessions", async (req, res) => {
  const instanceName = String(req.body?.instanceName || "")
    .trim()
    .toLowerCase();

  if (!instanceNamePattern.test(instanceName)) {
    return res.status(400).json({
      message:
        "Instance name must contain only lowercase letters, numbers, _ or -, and be 1-64 characters.",
    });
  }

  /**
   * Evolution instance token.
   *
   * This is different from the global Evolution API key.
   */
  const token = crypto.randomBytes(24).toString("hex");

  try {
    /**
     * IMPORTANT:
     *
     * Evolution API v2 requires the integration/channel.
     *
     * Without this:
     *
     *   integration: 'WHATSAPP-BAILEYS'
     *
     * Evolution returns:
     *
     *   Invalid integration
     *
     * and removes the instance.
     */
    const { data } = await evolutionRequest({
      method: "POST",
      url: "/instance/create",
      data: {
        instanceName,

        integration: "WHATSAPP-BAILEYS",

        token,

        qrcode: true,
      },
    });

    tokens.set(instanceName, token);

    return res.status(201).json({
      instanceName,
      tokenKnown: true,
      ...data,
    });
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   CONNECT / GET QR
   ========================================================= */

app.get("/api/sessions/:instance/connect", async (req, res) => {
  const instance = String(req.params.instance || "").trim();

  if (!instance) {
    return res.status(400).json({
      message: "Instance name is required",
    });
  }

  try {
    const { data } = await evolutionRequest({
      method: "GET",
      url: `/instance/connect/${encodeURIComponent(instance)}`,
    });

    return res.json(data);
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/**
 * QR endpoint.
 *
 * Evolution's connect endpoint returns the QR information,
 * so this endpoint intentionally uses the same Evolution route.
 */
app.get("/api/sessions/:instance/qr", async (req, res) => {
  const instance = String(req.params.instance || "").trim();

  if (!instance) {
    return res.status(400).json({
      message: "Instance name is required",
    });
  }

  try {
    const { data } = await evolutionRequest({
      method: "GET",
      url: `/instance/connect/${encodeURIComponent(instance)}`,
    });

    return res.json(data);
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   RESTART
   ========================================================= */

app.post("/api/sessions/:instance/restart", async (req, res) => {
  const instance = String(req.params.instance || "").trim();

  try {
    const { data } = await evolutionRequest({
      method: "PUT",
      url: `/instance/restart/${encodeURIComponent(instance)}`,
    });

    return res.json(data);
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   LOGOUT / DISCONNECT
   ========================================================= */

app.post("/api/sessions/:instance/disconnect", async (req, res) => {
  const instance = String(req.params.instance || "").trim();

  try {
    let data;

    /**
     * Evolution v2 normally uses:
     *
     * DELETE /instance/logout/:instance
     *
     * Keep the fallback for installations exposing
     * the older disconnect route.
     */
    try {
      ({ data } = await evolutionRequest({
        method: "DELETE",
        url: `/instance/logout/${encodeURIComponent(instance)}`,
      }));
    } catch (logoutError) {
      if (![404, 405].includes(logoutError?.response?.status)) {
        throw logoutError;
      }

      ({ data } = await evolutionRequest({
        method: "POST",
        url: `/instance/disconnect/${encodeURIComponent(instance)}`,
      }));
    }

    return res.json(data);
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   DELETE SESSION
   ========================================================= */

app.delete("/api/sessions/:instance", async (req, res) => {
  const instance = String(req.params.instance || "").trim();

  try {
    const { data } = await evolutionRequest({
      method: "DELETE",
      url: `/instance/delete/${encodeURIComponent(instance)}`,
    });

    tokens.delete(instance);

    return res.json(data);
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   SEND TEXT MESSAGE
   ========================================================= */

app.post("/api/sessions/:instance/send-text", async (req, res) => {
  const instance = String(req.params.instance || "").trim();

  /**
   * Keep only digits.
   *
   * Example:
   *
   * +91 98765 43210
   *
   * becomes:
   *
   * 919876543210
   */
  const number = String(req.body?.number || "").replace(/\D/g, "");

  const text = String(req.body?.text || "").trim();

  if (!number || !text) {
    return res.status(400).json({
      message: "number and text are required",
    });
  }

  try {
    const { data } = await evolutionRequest({
      method: "POST",
      url: `/message/sendText/${encodeURIComponent(instance)}`,
      data: {
        number,
        text,
      },
    });

    return res.json(data);
  } catch (error) {
    return sendEvolutionError(res, error);
  }
});

/* =========================================================
   STATIC FRONTEND
   ========================================================= */

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const clientDist = path.resolve(__dirname, "../../client/dist");

app.use(express.static(clientDist));

/**
 * SPA fallback.
 *
 * Do not intercept API requests.
 */
app.use((req, res, next) => {
  if (req.path.startsWith("/api/")) {
    return next();
  }

  return res.sendFile(path.join(clientDist, "index.html"), (error) => {
    if (error) {
      return next();
    }
  });
});

/* =========================================================
   START SERVER
   ========================================================= */

app.listen(port, () => {
  console.log(
    `Evolution WhatsApp Manager listening on http://localhost:${port}`,
  );

  console.log(`Evolution API: ${evolutionUrl || "(not configured)"}`);

  console.log(`Evolution API key: ${evolutionKey ? "configured" : "MISSING"}`);
});
